# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_vsclust_rcpp_hello_world', PACKAGE = 'vsclust')
}

fill_missing_vals_and_ratio <- function(feature_mat, missing_vals, ratio_missing_vals, missing_value = NA_real_) {
    invisible(.Call('_vsclust_fill_missing_vals_and_ratio', PACKAGE = 'vsclust', feature_mat, missing_vals, ratio_missing_vals, missing_value))
}

c_plusplus_means <- function(feature_mat, centers, weight, fuzz, dist_metric, iter_max, rel_tol, verbose, membership_mat, ermin, iter, missing_value = NA_real_, weight_missing = 0) {
    .Call('_vsclust_c_plusplus_means', PACKAGE = 'vsclust', feature_mat, centers, weight, fuzz, dist_metric, iter_max, rel_tol, verbose, membership_mat, ermin, iter, missing_value, weight_missing)
}

